requirejs([
    'common',
    'echart-outsourcing',
    'echart-funds',
    'echart-organizer',
    'echart-stage',
    'echart-priority',
    'echart-company',
    'echart-hosting',
    'echart-committee',
    'mychart-bar',
]);